export const users = [
    {
        userId: "ngj_user_1",
        traits: {
          name: "Emily Davis",
          email: "emily.davis@acme.com",
          company: "TechCorp Inc.",
          role: "Product Manager",
          plan: "Enterprise",
          signupDate: "2023-06-01",
          usageTier: "High",
          numUsers: 150,
        },
      },
      {
        userId: "ngj_user_2",
        traits: {
          name: "Michael Thompson",
          email: "michael.thompson@fintech.com",
          company: "FinServe LLC",
          role: "CTO",
          plan: "Professional",
          signupDate: "2023-07-15",
          usageTier: "Medium",
          numUsers: 50,
        },
      },
    //   {
    //     userId: "ngj_user_3",
    //     traits: {
    //       name: "Sophia Martinez",
    //       email: "sophia.martinez@healthcareplus.com",
    //       company: "Healthcare Plus",
    //       role: "Operations Manager",
    //       plan: "Premium",
    //       signupDate: "2023-05-20",
    //       usageTier: "High",
    //       numUsers: 200,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_4",
    //     traits: {
    //       name: "James Lee",
    //       email: "james.lee@retailco.com",
    //       company: "RetailCo",
    //       role: "Marketing Specialist",
    //       plan: "Basic",
    //       signupDate: "2023-08-10",
    //       usageTier: "Low",
    //       numUsers: 20,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_5",
    //     traits: {
    //       name: "Olivia Johnson",
    //       email: "olivia.johnson@startuplabs.io",
    //       company: "Startup Labs",
    //       role: "CEO",
    //       plan: "Ultimate",
    //       signupDate: "2023-01-15",
    //       usageTier: "High",
    //       numUsers: 5,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_6",
    //     traits: {
    //       name: "Liam Patel",
    //       email: "liam.patel@logisticsinc.com",
    //       company: "Logistics Inc.",
    //       role: "Supply Chain Analyst",
    //       plan: "Enterprise",
    //       signupDate: "2022-12-05",
    //       usageTier: "Medium",
    //       numUsers: 80,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_7",
    //     traits: {
    //       name: "Emma Davis",
    //       email: "emma.davis@greenenergy.com",
    //       company: "Green Energy Solutions",
    //       role: "Sustainability Advisor",
    //       plan: "Professional",
    //       signupDate: "2023-03-12",
    //       usageTier: "Medium",
    //       numUsers: 45,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_8",
    //     traits: {
    //       name: "Noah Wilson",
    //       email: "noah.wilson@financegroup.com",
    //       company: "Finance Group",
    //       role: "Financial Analyst",
    //       plan: "Professional",
    //       signupDate: "2023-04-01",
    //       usageTier: "Low",
    //       numUsers: 25,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_9",
    //     traits: {
    //       name: "Ava Brown",
    //       email: "ava.brown@techinnovators.com",
    //       company: "Tech Innovators",
    //       role: "Product Designer",
    //       plan: "Enterprise",
    //       signupDate: "2023-02-14",
    //       usageTier: "High",
    //       numUsers: 120,
    //     },
    //   },
    //   {
    //     userId: "ngj_user_10",
    //     traits: {
    //       name: "William Anderson",
    //       email: "william.anderson@constructionco.com",
    //       company: "Construction Co.",
    //       role: "Project Manager",
    //       plan: "Basic",
    //       signupDate: "2023-06-25",
    //       usageTier: "Low",
    //       numUsers: 15,
    //     },
    //   },
      {
        anonymousId: "ngj_anon_1",
        traits: {
          email: "jim@startup.io",
          company: "Startup.io",
          role: "Founder",
          lastVisited: "2023-08-10",
        },
      },
      {
        anonymousId: "ngj_anon_2",
        traits: {},
      }
  ]